### ISSUE TITLE
Improve trapezoidal(f::AbstractArray, x::AbstractRange)

### ISSUE THREAD

**Issue by pvalenzuelac** [loforteg/ECON622-PS4#1]
Hi,
I was trying to use your code but I found that the trapezoidal function when the type of `x` was an AbstractRange was not optimized. I think it would be faster with a ternary operator.

```julia
function trapezoidal(f::AbstractArray, x::AbstractRange)
    Δ = step(x)
    N = length(x)
    total = zero(eltype(x))
    
    for k=1:N
        weight = ((k == 1) || (k == N)) ?  Δ/2 : Δ 
        total += weight * f[k]
    end
    return total

end
``` 

Let me know what do you think!

**Comment by loforteg** [comment]
Hi Pablo!
You raise a very good point; I have modified my code accordingly.
Cheers!
